type Coords = { lat: number; lng: number };

export const countriesCoords: Record<string, Coords> = {
  "Ukraine": { lat: 50.45, lng: 30.52 },
  "Poland": { lat: 52.23, lng: 21.01 },
  "Germany": { lat: 52.52, lng: 13.40 },
  "France": { lat: 48.85, lng: 2.35 },
  "Italy": { lat: 41.90, lng: 12.49 },
  "Spain": { lat: 40.42, lng: -3.70 },
  "Portugal": { lat: 38.72, lng: -9.14 },
  "Netherlands": { lat: 52.37, lng: 4.90 },
  "Belgium": { lat: 50.85, lng: 4.35 },
  "Switzerland": { lat: 46.95, lng: 7.44 },
  "Austria": { lat: 48.21, lng: 16.37 },
  "Czech Republic": { lat: 50.08, lng: 14.43 },
  "Slovakia": { lat: 48.15, lng: 17.11 },
  "Hungary": { lat: 47.50, lng: 19.04 },
  "Romania": { lat: 44.43, lng: 26.10 },
  "Bulgaria": { lat: 42.70, lng: 23.32 },
  "Moldova": { lat: 47.01, lng: 28.86 },
  "Lithuania": { lat: 54.68, lng: 25.28 },
  "Latvia": { lat: 56.95, lng: 24.10 },
  "Estonia": { lat: 59.44, lng: 24.75 },
  "Sweden": { lat: 59.33, lng: 18.07 },
  "Norway": { lat: 59.91, lng: 10.75 },
  "Denmark": { lat: 55.68, lng: 12.57 },
  "Finland": { lat: 60.17, lng: 24.94 },
  "Iceland": { lat: 64.15, lng: -21.94 },
  "United Kingdom": { lat: 51.51, lng: -0.13 },
  "Ireland": { lat: 53.33, lng: -6.25 },
  "United States": { lat: 38.90, lng: -77.03 },
  "Canada": { lat: 45.42, lng: -75.69 },
  "Mexico": { lat: 19.43, lng: -99.13 },
  "Brazil": { lat: -15.79, lng: -47.88 },
  "Argentina": { lat: -34.60, lng: -58.38 },
  "Chile": { lat: -33.46, lng: -70.65 },
  "Australia": { lat: -35.28, lng: 149.13 },
  "New Zealand": { lat: -41.29, lng: 174.78 },
  "Japan": { lat: 35.68, lng: 139.76 },
  "South Korea": { lat: 37.56, lng: 126.97 },
  "China": { lat: 39.90, lng: 116.40 },
  "India": { lat: 28.61, lng: 77.21 },
  "Indonesia": { lat: -6.17, lng: 106.83 },
  "Thailand": { lat: 13.75, lng: 100.50 },
  "Vietnam": { lat: 21.03, lng: 105.85 },
  "Singapore": { lat: 1.35, lng: 103.82 },
  "Israel": { lat: 31.77, lng: 35.21 },
  "Turkey": { lat: 39.93, lng: 32.86 },
  "Egypt": { lat: 30.04, lng: 31.23 },
  "Morocco": { lat: 33.57, lng: -7.59 },
  "South Africa": { lat: -25.74, lng: 28.19 }
};

export const countrys = [
  { ua: 'Україна', en: 'Ukraine' },
  { ua: 'Польща', en: 'Poland' },
  { ua: 'Німеччина', en: 'Germany' },
  { ua: 'Франція', en: 'France' },
  { ua: 'Італія', en: 'Italy' },
  { ua: 'Іспанія', en: 'Spain' },
  { ua: 'Португалія', en: 'Portugal' },
  { ua: 'Нідерланди', en: 'Netherlands' },
  { ua: 'Бельгія', en: 'Belgium' },
  { ua: 'Швейцарія', en: 'Switzerland' },
  { ua: 'Австрія', en: 'Austria' },
  { ua: 'Чехія', en: 'Czech Republic' },
  { ua: 'Словаччина', en: 'Slovakia' },
  { ua: 'Угорщина', en: 'Hungary' },
  { ua: 'Румунія', en: 'Romania' },
  { ua: 'Болгарія', en: 'Bulgaria' },
  { ua: 'Молдова', en: 'Moldova' },
  { ua: 'Литва', en: 'Lithuania' },
  { ua: 'Латвія', en: 'Latvia' },
  { ua: 'Естонія', en: 'Estonia' },
  { ua: 'Швеція', en: 'Sweden' },
  { ua: 'Норвегія', en: 'Norway' },
  { ua: 'Данія', en: 'Denmark' },
  { ua: 'Фінляндія', en: 'Finland' },
  { ua: 'Ісландія', en: 'Iceland' },
  { ua: 'Велика Британія', en: 'United Kingdom' },
  { ua: 'Ірландія', en: 'Ireland' },
  { ua: 'США', en: 'United States' },
  { ua: 'Канада', en: 'Canada' },
  { ua: 'Мексика', en: 'Mexico' },
  { ua: 'Бразилія', en: 'Brazil' },
  { ua: 'Аргентина', en: 'Argentina' },
  { ua: 'Чилі', en: 'Chile' },
  { ua: 'Австралія', en: 'Australia' },
  { ua: 'Нова Зеландія', en: 'New Zealand' },
  { ua: 'Японія', en: 'Japan' },
  { ua: 'Південна Корея', en: 'South Korea' },
  { ua: 'Китай', en: 'China' },
  { ua: 'Індія', en: 'India' },
  { ua: 'Індонезія', en: 'Indonesia' },
  { ua: 'Таїланд', en: 'Thailand' },
  { ua: "В'єтнам", en: 'Vietnam' },
  { ua: 'Сінгапур', en: 'Singapore' },
  { ua: 'Ізраїль', en: 'Israel' },
  { ua: 'Туреччина', en: 'Turkey' },
  { ua: 'Єгипет', en: 'Egypt' },
  { ua: 'Марокко', en: 'Morocco' },
  { ua: 'ПАР', en: 'South Africa' }
];

/**
 * Функция возвращает координаты страны по названию на ua или en
 */
export function getCoordsByCountry(name: string): Coords | null {
  const country = countrys.find(c => c.ua === name || c.en === name);
  if (!country) return null;
  return countriesCoords[country.en] || null;
}
