version: '3.9'

services:
  app:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4173:4173"
    command: sh -c "bun install && bun run build && bun run preview --host 0.0.0.0"
    environment:
      - NODE_ENV=production
      - PORT=4173
